### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by AndreiTS** [pal1000/save-legacy-intel-graphics#5]
My friend couldn't play minecraft with his old notebook, but now he can. Thank you!

**Comment by RayBytes** [comment]
@AndreiTS just curious as to how you applied this to minecraft?

**Comment by AndreiTS** [comment]
> @AndreiTS just curious as to how you applied this to minecraft?

This was a long time ago, but I think I just intalled normally.

**Comment by mecyanned** [comment]
its been a year - did u find out how lmao

> > [@AndreiTS](https://github.com/AndreiTS) just curious as to how you applied this to minecraft?
> 
> This was a long time ago, but I think I just intalled normally.
