### ISSUE TITLE
ever heard of wtfi.exe patcher for exes? rewrites their manifest to allow win10 to load intel opengl...

### ISSUE THREAD

**Issue by neakmenter** [pal1000/save-legacy-intel-graphics#7]
https://github.com/alexey-lysiuk/tools/blob/master/wtfi/Release/wtfi.exe

It doesn't seem to be well documented, maybe you'd like to add it to your list of fixes??

BTW new to github - sorry if i've posted this in the wrong place...

**Comment by pal1000** [comment]
Everything's fine. I'll test this tool and see it manifest editing convenient for everyone.

**Comment by neakmenter** [comment]
I think the author  one of the contributors to the gzdoom project, if that's any useful information.
:)

**Comment by pal1000** [comment]
> 
> 
> I think the author one of the contributors to the gzdoom project, if that's any useful information.
> :)

OK.
